#/bin/bash

# path
export PATH=~/.dotfiles/ubuntu/bin:$PATH
export PATH="$PATH:/usr/bin"
export PATH="$PATH:/home/oren/.bin"

# android
export PATH="$PATH:/home/oren/apps/android-sdk-linux/tools"
export PATH="$PATH:/home/oren/apps/android-sdk-linux/platform-tools"
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
# export PATH="$PATH:/home/oren/apps/android-sdk-linux/build-tools"

# go
export PATH=$PATH:/usr/local/go/bin
export GOPATH='/home/oren/projects/go'
export PATH=$PATH:$GOPATH/bin

# env
export EDITOR="vim"
export PS1="\w "
export ANDROID_BIN="/home/oren/apps/android-sdk-linux/tools/android"
export GREP_OPTIONS="--color=auto"
export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export NODE_PATH=/usr/local/lib/node_modules

## amazon s3 configuration
if [[ -f ~/.amazon_keys ]]; then source ~/.amazon_keys; fi

# common aliases & functions

_gemset() {
  if [[ -z $GS_NAME ]]; then
    echo ""
  else
    echo "$GS_NAME "
  fi
}

_suspended() {
  jobs | wc -l | tr -d " "
}

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f ~/.git-completion ]; then
    . ~/.git-completion
fi
