#/bin/bash

# env
export EDITOR="vim"
export TERM=screen-256color
export PS1="\w "
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
export ANDROID_BIN="/home/oren/apps/android-sdk-linux/tools/android"

# path
export PATH=~/.dotfiles/ubuntu-work-desktop/bin:$PATH
export PATH="$PATH:/home/oren/apps/android-sdk-linux/tools"
export PATH="$PATH:/home/oren/apps/android-sdk-linux/platform-tools"
export PATH="$PATH:/home/oren/apps/android-sdk-linux/build-tools"

# go
export GOPATH=$HOME/projects/go
export PATH=$PATH:$GOPATH/bin

# export GOROOT=/usr/lib/go
# export GOBIN=/usr/bin/go

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f ~/.git-completion ]; then
    . ~/.git-completion
fi
