#/bin/bash

# bin
export PATH=~/.dotfiles/x1/bin:$PATH
export PATH=$PATH:$HOME/.bin

# env
export PS1="\w "
export EDITOR="vim"

# appengine
export PATH=$PATH:~/projects/go_appengine

# java
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64

# android
export ANDROID_BIN="/home/oren/Downloads/android-sdk-linux/tools/android"
export PATH="$PATH:/home/oren/Downloads/android-sdk-linux/tools"
export PATH="$PATH:/home/oren/Downloads/android-sdk-linux/platform-tools"
export PATH="$PATH:/home/oren/Downloads/android-sdk-linux/build-tools"

# go workspace
export GOPATH=$HOME/projects/go
export PATH=$PATH:$GOPATH/bin

# go binary
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin

# use vim for manpages
# export MANPAGER="sh -c \"col -b | vim -c 'set ft=man ts=8 nomod nolist nonu noma' -\""

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f ~/.git-completion ]; then
    . ~/.git-completion
fi

# The next line updates PATH for the Google Cloud SDK.
source '/home/oren/google-cloud-sdk/path.bash.inc'

# The next line enables bash completion for gcloud.
source '/home/oren/google-cloud-sdk/completion.bash.inc'
