#/bin/bash

# bin
export PATH=~/.dotfiles/ubuntu-x120e/bin:$PATH
export PATH=$PATH:$HOME/.bin

# env
export PS1="\w "
export EDITOR="vim"

# appengine
export PATH=$PATH:~/projects/go_appengine

# java
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64

# ec2
export EC2_HOME=/usr/local/ec2/ec2-api-tools-1.7.2.4
export PATH=$PATH:$EC2_HOME/bin

# android
export ANDROID_BIN="/home/oren/Downloads/android-sdk-linux/tools/android"
export PATH="$PATH:/home/oren/Downloads/android-sdk-linux/tools"
export PATH="$PATH:/home/oren/Downloads/android-sdk-linux/platform-tools"
export PATH="$PATH:/home/oren/Downloads/android-sdk-linux/build-tools"

# go workspace
export GOPATH=$HOME/projects/go
export PATH=$PATH:$GOPATH/bin

# go binary
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin

# #amazon s3 configuration
if [[ -f ~/.amazon_keys ]]; then source ~/.amazon_keys; fi

_suspended() {
  jobs | wc -l | tr -d " "
}

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f ~/.git-completion ]; then
    . ~/.git-completion
fi

