#/bin/bash

# bin
export PATH=~/.dotfiles/ubuntu-x120e/bin:$PATH

# env
export TERM=screen-256color
export PS1="\w "

# java
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64

# android
export ANDROID_BIN="/home/oren/apps/android-sdk-linux/tools/android"
export PATH="$PATH:/home/oren/apps/android-sdk-linux/tools"
export PATH="$PATH:/home/oren/apps/android-sdk-linux/platform-tools"
export PATH="$PATH:/home/oren/apps/android-sdk-linux/build-tools"

# go workspace
export GOPATH=$HOME/projects/go
export PATH=$PATH:$GOPATH/bin

# go binary
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin

# #amazon s3 configuration
if [[ -f ~/.amazon_keys ]]; then source ~/.amazon_keys; fi

_suspended() {
  jobs | wc -l | tr -d " "
}

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f ~/.git-completion ]; then
    . ~/.git-completion
fi
