#/bin/bash

export EDITOR="vim"
export PS1='\[\033[32m\]\w \[\033[00;34m\]$(echo $(br) $(_suspended)) \$\[\033[00m\] '
export PATH=~/.dotfiles/debian-server/bin:$PATH
export GREP_OPTIONS="--color=auto"
export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export NODE_PATH=/usr/local/lib/node_modules

# common aliases & functions

_suspended() {
  jobs | wc -l | tr -d " "
}

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
